# Generated by Django 5.1.4 on 2024-12-19 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='products_lo_name_2b03d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('images', models.ManyToManyField(related_name='products', to='products.image')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.location')),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='products_pr_title_7d8124_idx'), models.Index(fields=['location'], name='products_pr_locatio_6d2e4c_idx')],
            },
        ),
    ]
