# Generated by Django 5.1.4 on 2024-12-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_image2_image'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='location',
            name='products_lo_name_2b03d9_idx',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location',
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location'], name='products_lo_locatio_85b2e6_idx'),
        ),
    ]
